kind: Pod
apiVersion: v1
metadata: 
  labels:
    rollNo: PIAIC78340
    owner: Bilal
  name: ai-flask
spec: 
  containers:
  - name: assignment1
    image: bilaldeveloper/kubernetes-assignment-1:latest
    ports:
    - containerPort: 2020
